spring.application.name=spring-boot-url-shortner



app.base-url=http://localhost:8080
app.default-expiry-days=30
app.validate-original-url=true


spring.docker.compose.lifecycle-management=start_only
spring.datasource.url=jdbc:postgresql://localhost:5432/url-shortener-db
spring.datasource.username=priyanath
spring.datasource.password=P@B@titas$0220
spring.jpa.show-sql=true

#spring.jpa.hibernate.ddl-auto=update


spring.jpa.open-in-view=false